branches:
  only:
    - develop # next
    - master # 0.10
    - 0.9

language: php
dist: xenial
sudo: false

php: 
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - COMPOSER_ARGS=""
  - COMPOSER_ARGS="--prefer-lowest --prefer-stable"

before_install:
  - ./scripts/setup-travis.sh

install:
  - composer update ${COMPOSER_ARGS} --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose

cache:
  directories:
    - $HOME/.composer/cache/files
