branches:
  only:
    - develop
    - master
    - 0.5
    - 0.4
    - 0.3
    - 0.2
    - 0.1

language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

before_install:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - composer self-update

install:
  - composer update ${COMPOSER_ARGS} --dev --no-interaction

script:
  - phpunit --verbose

sudo: false
