branches:
  only:
    - develop # 0.8
    - master # 0.7
    - 0.6
    - 0.5
    - 0.4
    - 0.3
    - 0.2
    - 0.1

language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

before_install:
  - ./scripts/setup-travis.bash
  - composer self-update

install:
  - composer update ${COMPOSER_ARGS} --dev --no-interaction

script:
  - phpunit --verbose

sudo: false
