branches:
  only:
    - develop # 0.9
    - master # 0.8
    - 0.7

language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - COMPOSER_ARGS=""
  - COMPOSER_ARGS="--prefer-lowest --prefer-stable"

before_install:
  - ./scripts/setup-travis.bash

install:
  - composer update ${COMPOSER_ARGS} --dev --no-interaction

script:
  - phpunit --verbose

sudo: false
