branches:
  only:
    - develop
    - master
    - 0.4
    - 0.3
    - 0.2
    - 0.1

language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit -c phpunit.dist.xml
