branches:
  only:
    - develop
    - master
    - 0.5
    - 0.4
    - 0.3
    - 0.2
    - 0.1

language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - bash ./setup-travis.bash
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - phpunit --verbose
